import CryptoKit
import Foundation
@testable import PeekLicenseKit

/// TEST MATERIAL — NOT FOR PRODUCTION USE.
///
/// A fixed Ed25519 key pair plus three full interop vectors for
/// PeekLicenseKit's binary license format (schema_version 1, product_id 1).
///
/// The three `licenseString` values below are the **canonical** vectors,
/// produced by the actual license-issuing service (the Cloudflare Worker,
/// signing with @noble/ed25519) — copied verbatim from
/// `licensing-worker/TEST_VECTORS.md`. They are the ground truth for what a
/// real, production-shaped license string looks like for these inputs.
///
/// They are deliberately NOT generated by signing with CryptoKit in this
/// package. CryptoKit's Ed25519 signing is randomized: RFC 8032 defines a
/// deterministic nonce, but CryptoKit does not use it, so two calls to
/// `Curve25519.Signing.PrivateKey.signature(for:)` over the same message
/// produce two different, individually valid, signature bytes. A vector
/// "generated" that way is unreproducible by construction — not just across
/// machines, but across two runs on the same machine — so it cannot serve
/// as a fixed cross-implementation reference. (Both signatures verify fine;
/// only reproducibility is lost, not correctness.) The worker's
/// implementation does not have this property, which is why its output is
/// what's pinned here.
///
/// The private key is deterministically derived — SHA-256 of a fixed label
/// string — purely so it's reproducible from source instead of being an
/// opaque blob someone has to trust was copied correctly. It secures
/// nothing and must never be treated as a real signing key.
enum TestVectors {

    /// SHA-256("PeekLicenseKit-TEST-KEY-DO-NOT-USE-IN-PRODUCTION"),
    /// used as the raw 32-byte Ed25519 private key seed.
    static let privateKey: Curve25519.Signing.PrivateKey = {
        let seed = Data(SHA256.hash(data: Data("PeekLicenseKit-TEST-KEY-DO-NOT-USE-IN-PRODUCTION".utf8)))
        return try! Curve25519.Signing.PrivateKey(rawRepresentation: seed)
    }()

    static var publicKey: Curve25519.Signing.PublicKey { privateKey.publicKey }

    // Raw key material spelled out explicitly too, so the signing side can
    // cross-check its own derivation without running Swift/CryptoKit.
    static let privateKeyRawBase64 = "Y/Jxb3KfdzhvcaoziK5KJ4S63zpl9AiBif3bW5+JSs8="
    static let privateKeyRawHex = "63f2716f729f77386f71aa3388ae4a2784badf3a65f4088189fddb5b9f894acf"
    static let publicKeyRawBase64 = "5gho0wdlrodfH6kxcZfzMoz/EJNThgEd+0JHDQWm50E="
    static let publicKeyRawHex = "e60868d30765ae875f1fa9317197f3328cff10935386011dfb42470d05a6e741"

    struct Vector {
        let licenseString: String
        let email: String
        let issuedAtUnix: UInt32
        let polarKey: String
        let schemaVersion: UInt8 = 1
        let productID: UInt8 = 1
    }

    /// Three full, valid, schema-1 product-1 license strings, canonical
    /// output of the licensing-worker's signer for these inputs, alongside
    /// the exact field values each must decode to. Source:
    /// `licensing-worker/TEST_VECTORS.md` (regenerate there with
    /// `npm run vectors`, then copy the new strings here by hand).
    static let vectors: [Vector] = [
        Vector(
            licenseString: "PK3D-040PE-F1S00-CN0KT-C8592-TGA26-4S2TG-T46CT-2THA6-6MV2T-DSR74-R1EVB-1E9MP-YBKJD-XSQ6T-A0CNW-62VBG-DHJJW-RVFDM-YM364-33MH9-0JFXZ-8X667-9FDN4-6MX64-15EH3-2HXWF-8F2CE-K15PG-1H28N-X13N1-HE97R-H344N-J9XTC-6TW5B-MEH2N-4SHZ5-0KQ0R-W3T7S-05",
            email: "mario.rossi@example.com",
            issuedAtUnix: 1_732_000_000,
            polarKey: "POLAR-AB12-CD34-EF56-7890"
        ),
        Vector(
            licenseString: "PK3D-040P9-ETTG0-CN0KT-C8592-TC1G6-0R2TC-9H64R-JTCHJ-68S2T-CSK6C-SH8WV-FCDMP-AX63M-10C7A-BKCNP-Q0TBF-5SMQ8-VN6TX-ENZQB-QZ1YZ-MS5GG-EMYNB-EZJGF-3B0ED-BBGT4-2V0P2-61DAB-ARMJ7-M72E8-BKZMT-N4AYJ-Y3KCN-CM1PS-P1SZ7-6G3S3-396BG-CA5XB-830",
            email: "società@ésempio.it",
            issuedAtUnix: 1_690_000_000,
            polarKey: "POLAR-0000-1111-2222-3333"
        ),
        Vector(
            licenseString: "PK3D-040PP-JEJ00-CN0KT-C8592-TPJTB-9D2TE-9S74W-JTGA1-850JT-GJ289-11GWB-15DR6-ASBB6-DJ40R-BEEHM-74VVG-D5HJW-X35ED-T0NSE-3BYYR-D26WN-7PWB3-2STPE-ATN2K-5PAVJ-6H24B-J2RY2-446FE-Q5Z9D-9P0G3-PRVZR-1FHM7-KCCV9-YFKWJ-JET8R-DKACH-YGGZX-DNFCP-M514",
            email: "qa+peek3d@anthropic.test",
            issuedAtUnix: 1_800_000_000,
            polarKey: "POLAR-ZZZZ-9999-AAAA-BBBB"
        )
    ]
}
